import React from 'react'
import ScrollRestoration from './ScrollRestoration'
import { jost } from './fonts/fonts'
import './styles.scss'
import './normalize.scss'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
  const { children, modal } = props

  return (
    <html lang="en" className={`${jost.variable}`}>
      <body>
        <main>
          <ScrollRestoration />
          <div>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
