import React from 'react'
import { jost } from './fonts/fonts'
import './styles.scss'
import './normalize.scss'
import type { Metadata } from 'next'
import { ReactLenis, useLenis } from 'lenis/react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: {
  children: React.ReactNode
}) {
  const { children } = props

  return (
    <html lang="en" className={`${jost.variable}`}>
      <body>
        <ReactLenis />
        <main>
          <div>{children}</div>
        </main>
      </body>
    </html>
  )
}
